### ISSUE TITLE
Add Frame around Map

### ISSUE THREAD

**Issue by BenChaimberg** [TableTopTango/Geopollinator#2]
It's a weird look to have the map cut off on the sides or by the edge of the browser window.

**Comment by TableTopTango** [comment]
Whatcha up to Ben.

**Comment by BenChaimberg** [comment]
haha not much, just using Github a lot more for work so having this issue around kept confusing me

**Comment by TableTopTango** [comment]
Gotta get that frame around the map man. Can't just leave it like that.
